sii9024a: select required dependencies
Select HDMI common bits.

This fixes linker error:
~/msm7x30-3.0.x-nAa/drivers/video/msm/mdp4_overlay.c:277: undefined reference to « mdp_vid_quant_set »

Thanks to @M66B for the suggestion.

Signed-off-by: Adrien Tétar <adrien.tetar@hotmail.fr>